# Generated by Django 6.0.7 on 2026-07-17 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booking_guest_email_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('VEHICLE', 'Fleet'), ('CUSTOMER', 'With Customers'), ('DESTINATION', 'On the Road')], default='CUSTOMER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, help_text='e.g. Kunzum La, Spiti Valley', max_length=150)),
                ('customer_name', models.CharField(blank=True, max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='travel.tourpackage')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_photos', to='travel.vehicle')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
