# Generated by Django 6.0.7 on 2026-07-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
    ]
